name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Format codebase
      run: npm run format
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run precommit-test